-- refresh_mv_daily_work_summary.sql — BAT-010: mv_daily_work_summary リフレッシュ
-- 権威ドキュメント:
--   docs/05_詳細設計/07_アルゴリズム詳細設計/06_バッチジョブ処理詳細（BAT-001〜010）.md §11 BAT-010
--   docs/05_詳細設計/01_データベース詳細設計/04_ビュー・マテリアライズドビュー設計（VWカタログ）.md
--
-- 目的: VW-006 mv_daily_work_summary マテリアライズドビューを最新データで更新する
-- 実行タイミング: BAT-010 RP-006 集計レポート生成の Step 1（最初に実行する）
--   - 日次: 毎日 06:00 JST
--   - 週次: 毎週月曜日 07:00 JST
--   - 月次: 毎月 1 日 07:00 JST
--
-- REFRESH CONCURRENTLY の条件:
--   CONCURRENTLY は idx_mv_daily_work_summary_pk（UNIQUE INDEX）が必要。
--   V20260517120057 で作成済み。
--   CONCURRENTLY は SELECT ロックのみで実行され、MV 読み取りをブロックしない。
--
-- 注意:
--   CONCURRENTLY はトランザクション内では使用できない。
--   本スクリプトは単独で実行すること（BEGIN/COMMIT で囲まない）。

-- mv_daily_work_summary を CONCURRENTLY でリフレッシュする
-- ダッシュボードやレポートへの影響を最小化するため排他ロックを取得しない
REFRESH MATERIALIZED VIEW CONCURRENTLY mv_daily_work_summary;
